### PR TITLE
Arity transparency with Object.defineProperty

### LINKED ISSUE #2: Doesn't retain arity
I'd like to refrain from switching to sinon or something.

Here's an example:
https://github.com/sinonjs/sinon/pull/681/files

### PR DESCRIPTION
**Pull request by mightyiam**
Fixes #2

### CODE REVIEW

**Comment by tjoskar** [comment]
Nice solution! Thanks @mightyiam 🎉

**Comment by mightyiam** [comment]
Great! Do I get a release, @tjoskar ?

**Comment by tjoskar** [comment]
Yes, [2.0.4](https://github.com/tjoskar/simple-spy/releases/tag/v2.0.4) is [out](https://www.npmjs.com/package/simple-spy).

**Comment by mightyiam** [comment]
Thank you!

**Pull request merged**
